### ISSUE TITLE
Data selection

### ISSUE THREAD

**Issue by dataubc** [UBC-MDS/DSCI_522_group-314#2]
Hello friends,
I am just opening this issue to start brainstorming for ideas regarding the data selection and research questions.
Thanks,

**Comment by ribner** [comment]
I find this dataset interesting: https://data.world/raghu543/credit-card-fraud-data
I think fraud is an interesting problem to solve and plays on some of the things we are learning in feature model selection, having highly unbalanced data. Downloading the data requires login, so if we were to use it i would probably have to make the data accessible via a direct url.

**Comment by ribner** [comment]
Here is another data set I like: https://www.kaggle.com/c/loan-default-prediction/data , the problem here is to estimate loan default prediction. Going one step further, you might choose to optimize the portfolio (rather than simply predict loan defaults), which makes for an interesting problem. That way there is a clearly optimal solution, which is not always the case in  these classification problems where you need to arbitrarily choose the optimal precision and recall rates. Using a kaggle data set can be problematic for downloading but it appears there is a kaggle cli, with that i think we can make it easily downloadable. IE
```
pip install kaggle
export KAGGLE_USERNAME=dummyacount@dummy.com
export KAGGLE_KEY=dummypassword
kaggle competitions download -c loan-default-prediction
```

alternatively, we could use a more open data set for defaults: https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients

**Comment by dataubc** [comment]
I am totally for fraud detection problem and I would prefer to go with the open data option so the results can be reproducible by any users without the need for login credential. From my end, I would be also interested in the area of energy consumption ( renewable energy and fossil fuel) over the year and what is the data tell us about in terms of how much energy we will be need in the future ( prediction research question). The data is available from the world bank web site without the need to log in . For example the link is for the global renewable energy consumption over the years
https://data.worldbank.org/indicator/EG.FEC.RNEW.ZS
Let's us discuss this more in our meeting today.

**Comment by ribner** [comment]
As a team, we have decided on this dataset: https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients
